/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Tracker;

import java.io.*;
import java.util.HashMap;

import Tracker.Infrastructure.HttpServer.Server;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        HashMap<String, String> params = parseCommandLine(args);
        int serverPort = Integer.parseInt( params.getOrDefault("-p", "2025") ); // server port number
        System.out.println("starting the server on port " + serverPort);
        Server server = new Server(serverPort);
		server.run();
    }

    	// parse command line arguments
	private static HashMap<String, String> parseCommandLine(String[] args) {
		HashMap<String, String> params = new HashMap<String, String>();

		int i = 0;
		while ((i + 1) < args.length) {
			params.put(args[i], args[i+1]);
			i += 2;
		}
		
		return params;
	}
}
